//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlitterDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostReaction
    {
        public int id { get; set; }
        public int Post_id { get; set; }
        public int user_id { get; set; }
        public bool Reaction { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
